version: '3.8'

services:
  app:
    container_name: latex-app-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    volumes:
      - /app/node_modules
    restart: always
