version: '3.8'
services:
  app:
    container_name: latex-app-frontend
    image: node:20
    build: .
    ports:
      - "5173:4173"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: always
